apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace: chatapp
type: Opaque
data:
  jwt: ZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjNE1EUTVPVFl4TlN3aWFXRjBJam94Tnpnd05EazVOakUxZlE=
